[package]
name = "document"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
rusty-s3 = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
sea-orm = { workspace = true }
orm = { workspace = true }
chrono = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
